#Requires -RunAsAdministrator
# ============================================================
#  Jump — Developer Machine Setup
#  Run this from an elevated (Administrator) PowerShell prompt.
#  It installs all prerequisites, detects MSVC paths, generates
#  build_env.ps1, configures the project, builds, tests, and
#  runs the coverage gate.
# ============================================================

$ErrorActionPreference = "Stop"

Write-Host "============================================================"
Write-Host " Jump — Developer Environment Setup"
Write-Host "============================================================"
Write-Host ""

# ============================================================
#  1. Install prerequisites via Chocolatey
# ============================================================
Write-Host "[1/7] Checking prerequisites..."

if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
    Write-Host "  Installing Chocolatey..."
    [System.Net.ServicePointManager]::SecurityProtocol = 3072
    Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    $env:PATH = "$env:ALLUSERSPROFILE\chocolatey\bin;$env:PATH"
}
Write-Host "  Chocolatey: OK"

if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Host "  Installing Git..."
    choco install git -y --no-progress
} else {
    Write-Host "  Git: OK"
}

if (-not (Get-Command cmake -ErrorAction SilentlyContinue)) {
    Write-Host "  Installing CMake..."
    choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y --no-progress
} else {
    Write-Host "  CMake: OK"
}

$occPath = "C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe"
if (-not (Get-Command OpenCppCoverage -ErrorAction SilentlyContinue) -and -not (Test-Path $occPath)) {
    Write-Host "  Installing OpenCppCoverage..."
    choco install opencppcoverage -y --no-progress
} else {
    Write-Host "  OpenCppCoverage: OK"
}

# Visual Studio Build Tools
$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vswhere)) {
    Write-Host "  Installing Visual Studio Build Tools 2022..."
    choco install visualstudio2022buildtools -y --no-progress `
        --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"
    $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
}
Write-Host "  Visual Studio Build Tools: OK"
Write-Host ""

# ============================================================
#  2. Detect MSVC and Windows SDK paths
# ============================================================
Write-Host "[2/7] Detecting MSVC and Windows SDK paths..."

# List all VS installations (including BuildTools) and pick one with C++ headers
$vsRoots = & $vswhere -all -products * -property installationPath 2>$null
if (-not $vsRoots) {
    Write-Error "Could not find any Visual Studio installation."
    exit 1
}

$vsRoot  = $null
$msvcDir = $null
foreach ($candidate in $vsRoots) {
    $base = "$candidate\VC\Tools\MSVC"
    if (-not (Test-Path $base)) { continue }
    $ver = Get-ChildItem $base -Directory | Sort-Object Name -Descending | Select-Object -First 1 -ExpandProperty Name
    if ($ver -and (Test-Path "$base\$ver\include")) {
        $vsRoot  = $candidate
        $msvcDir = "$base\$ver"
        break
    }
}
if (-not $msvcDir) {
    Write-Error "No Visual Studio installation with complete MSVC C++ headers found."
    exit 1
}
Write-Host "  VS install: $vsRoot"
Write-Host "  MSVC: $msvcDir"

# Find Windows SDK
$winkitsDir = "${env:ProgramFiles(x86)}\Windows Kits\10"
$winkitsVer = Get-ChildItem "$winkitsDir\Include" -Directory | Sort-Object Name -Descending | Select-Object -First 1 -ExpandProperty Name
if (-not $winkitsVer) {
    Write-Error "No Windows SDK found under $winkitsDir\Include"
    exit 1
}
Write-Host "  Windows SDK: $winkitsVer"
Write-Host ""

# ============================================================
#  3. Generate build_env.ps1 with detected paths
# ============================================================
Write-Host "[3/7] Generating build_env.ps1..."

@"
# Auto-generated by setup_dev.ps1 — regenerate with: .\setup_dev.ps1
# Setup MSVC x64 environment.

`$MSVC_DIR    = "$msvcDir"
`$WINKITS_DIR = "$winkitsDir"
`$WINKITS_VER = "$winkitsVer"

`$env:PATH    = "`$MSVC_DIR\bin\Hostx64\x64;`$WINKITS_DIR\bin\`$WINKITS_VER\x64;C:\Program Files\CMake\bin;`$env:PATH"
`$env:INCLUDE = "`$MSVC_DIR\include;`$WINKITS_DIR\include\`$WINKITS_VER\ucrt;`$WINKITS_DIR\include\`$WINKITS_VER\um;`$WINKITS_DIR\include\`$WINKITS_VER\shared;`$WINKITS_DIR\include\`$WINKITS_VER\winrt"
`$env:LIB     = "`$MSVC_DIR\lib\x64;`$WINKITS_DIR\lib\`$WINKITS_VER\ucrt\x64;`$WINKITS_DIR\lib\`$WINKITS_VER\um\x64"

# Execute whatever is passed as arguments
if (`$args.Count -gt 0) {
    & `$args[0] `$args[1..(`$args.Count - 1)]
    exit `$LASTEXITCODE
}
"@ | Set-Content -Path "build_env.ps1" -Encoding UTF8

Write-Host "  build_env.ps1 written."
Write-Host ""

# ============================================================
#  4. Configure
# ============================================================
Write-Host "[4/7] Configuring project (CMake)..."
& .\build_env.ps1 cmake -B build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON
if ($LASTEXITCODE -ne 0) { Write-Error "CMake configure failed."; exit 1 }
Write-Host ""

# ============================================================
#  5. Build
# ============================================================
Write-Host "[5/7] Building (Debug)..."
& .\build_env.ps1 cmake --build build
if ($LASTEXITCODE -ne 0) { Write-Error "Build failed."; exit 1 }
Write-Host ""

# ============================================================
#  6. Test
# ============================================================
Write-Host "[6/7] Running tests..."
& .\build_env.ps1 ctest --test-dir build --output-on-failure
if ($LASTEXITCODE -ne 0) { Write-Error "Tests failed."; exit 1 }
Write-Host ""

# ============================================================
#  7. Coverage
# ============================================================
Write-Host "[7/7] Running coverage check..."
& .\check_coverage.ps1
if ($LASTEXITCODE -ne 0) {
    Write-Host "WARNING: Coverage gate failed. See output above."
} else {
    Write-Host "  Coverage gate passed."
}
Write-Host ""

Write-Host "============================================================"
Write-Host " Setup complete!"
Write-Host ""
Write-Host "  Quick reference:"
Write-Host "    .\build_env.ps1 cmake --build build                          Build"
Write-Host "    .\build_env.ps1 ctest --test-dir build --output-on-failure   Test"
Write-Host "    .\check_coverage.ps1                                         Coverage"
Write-Host "============================================================"
